# Generated by Django 2.2.10 on 2020-08-25 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='playergameinfo',
            name='is_answer_true',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='playergameinfo',
            name='number_answer',
            field=models.IntegerField(null=True),
        ),
    ]
